language: elixir
elixir:
- 1.4
env:
- MIX_ENV=test
addons:
  postgresql: '9.4'
services:
- postgresql
before_script:
- cp config/travis.exs config/test.exs
- mix ecto.create
- mix ecto.migrate
script:
- mix test